POST_REQUEST = 'POST'
GET_REQUEST = 'GET'
PUT_REQUEST = 'PUT'
DATE_FORMAT = '%Y-%m-%d'
DATETIME_FORMAT = '%Y-%m-%dT%H:%M:%S'
ISO8601_FORMAT = '%Y-%m-%dT%H:%M:%S.%fZ'

ADD_GROUP = 'add_group'
VIEW_GROUP = 'view_group'
ADD_USER = 'add_user'
VIEW_USER = 'view_user'

BASE_PERMISSION_CODES = (
    ADD_GROUP,
    VIEW_GROUP,
    ADD_USER,
    VIEW_USER,
)

DEVELOPER_ROLE_NAME = 'Developer'
TESTER_ROLE_NAME = 'User'
ORGANIZATION_ADMIN_ROLE_NAME = 'Admin'
NONE_ROLE_NAME = 'None'

ROLES = (
    # (DEVELOPER_ROLE_NAME, DEVELOPER_ROLE_NAME),
    (TESTER_ROLE_NAME, TESTER_ROLE_NAME),
    (ORGANIZATION_ADMIN_ROLE_NAME, ORGANIZATION_ADMIN_ROLE_NAME),
    # (NONE_ROLE_NAME, NONE_ROLE_NAME),
)
